Repository rush-db/rushdb, pull requests merged in 2025-01, with the labels that each got.

#51 feat: renew records.mdx, added aggregation part
  docs/.editorconfig
  docs/docs/advanced/search-aggregation.md
  docs/docs/basic-concepts/properties.md
  docs/docs/basic-concepts/properties.mdx
  docs/docs/basic-concepts/records.mdx
  docs/docs/basic-concepts/relations.mdx
  docs/docs/basic-concepts/transactions.mdx
  docs/docs/quick-start/configuring-dashboard.md
  docs/docs/working-with-rushdb-sdk/typescript-reference/rushdb-property.md
  docs/docs/working-with-rushdb-sdk/typescript-reference/rushdb-record-instance.md
  docs/docs/working-with-rushdb-sdk/typescript-reference/rushdb-record.md
  docs/static/img/quick-start/api-keys-screen.png
  docs/static/img/quick-start/create-project-screen.png
  docs/static/img/quick-start/create-token-screen.png
Labels: documentation

#85 feat: extended plans with START plan
  .changeset/tidy-monkeys-love.md
  platform/core/src/dashboard/billing/stripe/interfaces/stripe.constans.ts
  platform/core/src/dashboard/billing/stripe/interfaces/stripe.types.ts
  platform/core/src/dashboard/billing/stripe/plans.dto.ts
  platform/core/src/dashboard/billing/stripe/stripe.service.ts
  platform/core/src/dashboard/workspace/workspace.constants.ts
  platform/core/src/dashboard/workspace/workspace.service.ts
  platform/dashboard/src/features/auth/components/UserMenu.tsx
  platform/dashboard/src/features/billing/stores/plans.ts
  platform/dashboard/src/features/billing/types.ts
  platform/dashboard/src/pages/workspace/billing.tsx
  website/src/hooks/useBillingData.ts
  website/src/sections/Pricing.tsx
Labels: enhancement, dashboard

#87 chore: updated secrets
  .changeset/green-shirts-help.md
Labels: core

#92 fix: support for production aws (billing)
  .changeset/five-apples-switch.md
  platform/core/src/common/utils/isProductionMode.ts
  platform/core/src/dashboard/billing/stripe/stripe.service.ts
Labels: enhancement

#97 Update docs, minor fixes and cleanups
  .changeset/popular-gorillas-sort.md
  docs/docs/advanced/_category_.json
  docs/docs/advanced/data-types.md
  docs/docs/advanced/enhanced-typescript.md
  docs/docs/advanced/index.md
  docs/docs/advanced/properties.md
  docs/docs/advanced/querying-data.md
  docs/docs/advanced/records.md
  docs/docs/advanced/relationships.md
  docs/docs/advanced/search-aggregation.md
  docs/docs/advanced/search.md
  docs/docs/basic-concepts/records.mdx
  docs/docs/index.mdx
  docs/docs/quick-start/creating-and-retrieving-records.md
  docs/docs/quick-start/installation.md
  docs/docs/quick-start/local-platform-setup.md
  docs/docusaurus.config.ts
  docs/sidebars.ts
  docs/src/components/ColumnLayout/columns.module.css
  docs/src/components/ColumnLayout/index.tsx
  docs/src/components/HomepageFeatures/index.tsx
  docs/src/components/HomepageFeatures/styles.module.css
  docs/src/css/custom.css
  docs/src/pages/index.module.css
  docs/src/pages/index.tsx
  docs/src/pages/markdown-page.md
  packages/javascript-sdk/src/api/api.ts
  packages/javascript-sdk/src/api/create-api.ts
  packages/javascript-sdk/src/sdk/record.ts
  packages/javascript-sdk/src/types/query.ts
  platform/core/docker-compose.yml
  platform/core/neo4j/plugins/apoc-5.25.1-core.jar
  platform/core/src/core/common/normalizeRecord.ts
  platform/core/src/core/entity/dto/create-entity.dto.ts
  platform/core/src/core/entity/import-export/validation/schemas/import.schema.ts
  platform/core/src/core/entity/label.controller.ts
  platform/core/src/core/property/property-query.service.ts
  platform/core/src/core/property/property.controller.ts
  platform/core/src/core/property/property.service.ts
  platform/core/src/core/property/validation/property-values.pipe.ts
  platform/core/src/dashboard/project/project-query.service.ts
  platform/core/src/dashboard/user/user.module.ts
  platform/core/src/database/database.module.ts
  website/public/sitemap-0.xml
  website/src/sections/Hero/index.tsx
  website/src/sections/HowItWorks/index.tsx
Labels: documentation, SDK, core
